//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMVTheaterAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMVTheaterAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v3.0.0 | MIT License | git.io/normalize */
        ///html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}
        ///article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}
        ///audio,canvas,progress,video{display:inline-block;vertical-align:baseline}
        ///audio:not([controls]){display:none;height:0}
        ///[hidden],template{display:none}
        ///a{background:0 0}
        ///a:active,a:hover{outline:0}
        ///abbr[title]{border-bottom:1px dotted}
        ///b,strong{font-weight: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_css {
            get {
                return ResourceManager.GetString("default_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;AMV Theater Assistant (powered by MPC-HC WebServer)&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;default.css&quot;&gt;
        ///        &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;!--[if lt IE 8]&gt;
        ///            &lt;div class=&quot;browser-warning&quot;&gt;&lt;strong&gt;Warning!&lt;/strong&gt; You are using an &lt;strong&gt;outdated&lt;/strong&gt; browser. Please &lt;a href=&quot;http://browsehappy.com/&quot;&gt;upgrade your browser&lt;/a&gt; to improve your experi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v2.2.3
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright jQuery Foundation and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2016-04-05T19:26Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper `window`
        ///		// is present, execute the factory and get jQuery.
        ///		// For envi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_2_3 {
            get {
                return ResourceManager.GetString("jquery_2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(window).load(function(){
        ///	$( document ).ready(function() {
        ///		ReloadData()
        ///		setInterval(function(){ReloadData()}, 1500);
        ///	});
        ///
        ///
        ///	function ReloadData(){
        ///
        ///		$.get( &quot;panelinfo.txt&quot;, function( panelinfo ) {
        ///			var videoinfo = &quot;Nothing&quot;;
        ///
        ///$.ajax({
        ///	url: &apos;/info.html&apos;,
        ///	type: &apos;get&apos;,
        ///	dataType: &apos;text&apos;,
        ///	async: false,
        ///	success: function( filename ) {
        ///
        ///	if (filename.length &gt; 0) {
        ///	filename = filename.substring(0, filename.length-4);
        ///	videoinfo = filename;
        ///	}
        ///
        ///	} 
        ///});
        ///		
        ///			var panelinfo = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string panelinfo {
            get {
                return ResourceManager.GetString("panelinfo", resourceCulture);
            }
        }
    }
}
