//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMVTheaterAssistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to the AMV Theater")]
        public string pageTitleLine1 {
            get {
                return ((string)(this["pageTitleLine1"]));
            }
            set {
                this["pageTitleLine1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableTitleLine2 {
            get {
                return ((bool)(this["enableTitleLine2"]));
            }
            set {
                this["enableTitleLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pageTitleLine2 {
            get {
                return ((string)(this["pageTitleLine2"]));
            }
            set {
                this["pageTitleLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string title1Font {
            get {
                return ((string)(this["title1Font"]));
            }
            set {
                this["title1Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string title1Size {
            get {
                return ((string)(this["title1Size"]));
            }
            set {
                this["title1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string title2Font {
            get {
                return ((string)(this["title2Font"]));
            }
            set {
                this["title2Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string title2Size {
            get {
                return ((string)(this["title2Size"]));
            }
            set {
                this["title2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string panelInfoFont {
            get {
                return ((string)(this["panelInfoFont"]));
            }
            set {
                this["panelInfoFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string panelInfoSize {
            get {
                return ((string)(this["panelInfoSize"]));
            }
            set {
                this["panelInfoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string presentersFont {
            get {
                return ((string)(this["presentersFont"]));
            }
            set {
                this["presentersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string presentersSize {
            get {
                return ((string)(this["presentersSize"]));
            }
            set {
                this["presentersSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string videoInfoFont {
            get {
                return ((string)(this["videoInfoFont"]));
            }
            set {
                this["videoInfoFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public string videoInfoSize {
            get {
                return ((string)(this["videoInfoSize"]));
            }
            set {
                this["videoInfoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string upcoming1Font {
            get {
                return ((string)(this["upcoming1Font"]));
            }
            set {
                this["upcoming1Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string upcoming1Size {
            get {
                return ((string)(this["upcoming1Size"]));
            }
            set {
                this["upcoming1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Helvetica")]
        public string upcoming2Font {
            get {
                return ((string)(this["upcoming2Font"]));
            }
            set {
                this["upcoming2Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string upcoming2Size {
            get {
                return ((string)(this["upcoming2Size"]));
            }
            set {
                this["upcoming2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string siteLocation {
            get {
                return ((string)(this["siteLocation"]));
            }
            set {
                this["siteLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysOnTop {
            get {
                return ((bool)(this["alwaysOnTop"]));
            }
            set {
                this["alwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int defaultPlayMonitor {
            get {
                return ((int)(this["defaultPlayMonitor"]));
            }
            set {
                this["defaultPlayMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string cssBGcolor {
            get {
                return ((string)(this["cssBGcolor"]));
            }
            set {
                this["cssBGcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string cssTextColor {
            get {
                return ((string)(this["cssTextColor"]));
            }
            set {
                this["cssTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string cssTextSize {
            get {
                return ((string)(this["cssTextSize"]));
            }
            set {
                this["cssTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13579")]
        public string mpcWebPort {
            get {
                return ((string)(this["mpcWebPort"]));
            }
            set {
                this["mpcWebPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mpcAppLocation {
            get {
                return ((string)(this["mpcAppLocation"]));
            }
            set {
                this["mpcAppLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mpcEnableCustom {
            get {
                return ((bool)(this["mpcEnableCustom"]));
            }
            set {
                this["mpcEnableCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mpcStartFull {
            get {
                return ((bool)(this["mpcStartFull"]));
            }
            set {
                this["mpcStartFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string title1SizeType {
            get {
                return ((string)(this["title1SizeType"]));
            }
            set {
                this["title1SizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string title2SizeType {
            get {
                return ((string)(this["title2SizeType"]));
            }
            set {
                this["title2SizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string panelInfoSizeType {
            get {
                return ((string)(this["panelInfoSizeType"]));
            }
            set {
                this["panelInfoSizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string presentersSizeType {
            get {
                return ((string)(this["presentersSizeType"]));
            }
            set {
                this["presentersSizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string videoInfoSizeType {
            get {
                return ((string)(this["videoInfoSizeType"]));
            }
            set {
                this["videoInfoSizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string upcoming1SizeType {
            get {
                return ((string)(this["upcoming1SizeType"]));
            }
            set {
                this["upcoming1SizeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixels")]
        public string upcoming2SizeType {
            get {
                return ((string)(this["upcoming2SizeType"]));
            }
            set {
                this["upcoming2SizeType"] = value;
            }
        }
    }
}
